# Generated by Django 3.0.7 on 2020-07-01 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('map', '0001_initial'), ('map', '0002_auto_20200608_2201'), ('map', '0003_auto_20200608_2203'), ('map', '0004_auto_20200608_2305'), ('map', '0005_signuptoken'), ('map', '0006_event_user'), ('map', '0007_event_city')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupToken',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referrer', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(default='', max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('temp', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
