# Generated by Django 3.0.7 on 2020-06-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200608_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
