# Generated by Django 3.0.7 on 2020-06-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
